enabled: false
namespace:
  name: trillian-system
  create: false
serviceAccount:
  name: trillian-logserver
  annotations: {}
  create: false
spec:
  replicaCount: 1
  image: ghcr.io/sigstore/scaffolding/updatetree:v0.7.15@sha256:710945f110f08b01802ce0b050cac9ae55b93546c69840e54cd0fda7c8831434
ttlSecondsAfterFinished: 3600
securityContext:
  runAsNonRoot: true
  runAsUser: 65533
args:
  treeID: ""
   # -- valid tree states are ACTIVE, FROZEN and DRAINING
  treeState: ""
annotations: {}

# Configure Trillian dependency
trillian:
  namespace: trillian-system
  adminServer: ""
  logServer:
    name: trillian-logserver
    portRPC: 8091

tolerations: []
nodeSelector: {}
affinity: {}
